### ISSUE TITLE
uninitialized constant Zold::Stress::Pmnts::SecureRandom

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-stress#2]
```
ERROR: NameError: uninitialized constant Zold::Stress::Pmnts::SecureRandom
Did you mean?  SecurityError
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:85:in `pay_one'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:63:in `block (3 levels) in send'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:60:in `loop'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:60:in `block (2 levels) in send'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:54:in `loop'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:54:in `block in send'
	/Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/pmnts.rb:52:in `send'
	/Volumes/ssd2/code/zold/zold-stress/lib/zold/stress/round.rb:93:in `send'
	/Volumes/ssd2/code/zold/zold-stress/bin/zold-stress:112:in `block in <top (required)>'
	/Volumes/ssd2/code/zold/zold-stress/bin/zold-stress:109:in `times'
	/Volumes/ssd2/code/zold/zold-stress/bin/zold-stress:109:in `<top (required)>'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/zold-stress:22:in `load'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/zold-stress:22:in `<main>'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-stress#2` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
