### ISSUE TITLE
ERROR: NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-stress#3]
```
ERROR: NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/lib/zold/stress/stats.rb:54:in `sum'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/lib/zold/stress/stats.rb:50:in `avg'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/lib/zold/stress/summary.rb:43:in `tps'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/lib/zold/stress/summary.rb:48:in `to_s'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:139:in `puts'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:139:in `puts'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:139:in `print'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:125:in `info'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:70:in `block in info'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:69:in `synchronize'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.16.18/lib/zold/log.rb:69:in `info'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/bin/zold-stress:130:in `block in <top (required)>'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/bin/zold-stress:126:in `times'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-stress-0.2.0/bin/zold-stress:126:in `<top (required)>'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/zold-stress:22:in `load'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/zold-stress:22:in `<main>'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	/Users/yegor/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-stress#3` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
